package com.avbooknest.notification.model;

public enum NotificationType {
  ORDER_PLACED,
  BOOK_RESERVED,
  SHIPMENT_ACCEPTED,
  AWB_CREATED,
  SHIPMENT_IN_TRANSIT,
  SHIPMENT_DELIVERED,
  ORDER_CANCELLED,
  PAYMENT_SUCCEEDED,
  PAYMENT_REFUNDED,
  SELLER_TRANSFER_CREATED
}
