package com.avbooknest.config.seed;

import java.math.BigDecimal;
import java.util.List;

final class DevSeedData {

  static final String BUYER_EMAIL = "ana.popescu@booknest.local";

  static final List<UserSeed> USERS =
      List.of(
          new UserSeed("Ana", "Popescu", BUYER_EMAIL, "USER"),
          new UserSeed("Mihai", "Ionescu", "mihai.ionescu@booknest.local", "USER"),
          new UserSeed("Elena", "Marinescu", "elena.marinescu@booknest.local", "USER"),
          new UserSeed("Radu", "Georgescu", "radu.georgescu@booknest.local", "USER"),
          new UserSeed("Admin", "BookNest", "admin@booknest.local", "ADMIN"));

  static final List<CategorySeed> CATEGORIES =
      List.of(
          new CategorySeed(
              "Literatură clasică", "literatura-clasica", "Romane care au trecut testul timpului."),
          new CategorySeed(
              "Ficțiune contemporană",
              "fictiune-contemporana",
              "Povești actuale și voci literare moderne."),
          new CategorySeed("Fantasy", "fantasy", "Lumi imaginare, mituri și aventuri."),
          new CategorySeed(
              "Mister & thriller",
              "mister-thriller",
              "Investigații, suspans și răsturnări de situație."),
          new CategorySeed(
              "Dezvoltare personală",
              "dezvoltare-personala",
              "Idei practice pentru obiceiuri și echilibru."),
          new CategorySeed("Știință", "stiinta", "Descoperiri despre lume și univers."),
          new CategorySeed("Istorie", "istorie", "Evenimente și oameni care au modelat lumea."),
          new CategorySeed(
              "Copii", "copii", "Povești pentru cititorii aflați la început de drum."));

  static final List<BookSeed> BOOKS =
      List.of(
          book(
              "9780525559474",
              "Biblioteca de la miezul nopții",
              "Matt Haig",
              "Între viață și moarte există o bibliotecă în care fiecare volum deschide o altă posibilitate.",
              "39.90",
              "VERY_GOOD",
              "Română",
              "Nemira",
              2021,
              "elena.marinescu@booknest.local",
              "fictiune-contemporana",
              "AVAILABLE"),
          book(
              "9789734670482",
              "Numele trandafirului",
              "Umberto Eco",
              "Un mister medieval despre cărți, idei și o bibliotecă primejdioasă.",
              "47.50",
              "GOOD",
              "Română",
              "Polirom",
              2018,
              "mihai.ionescu@booknest.local",
              "mister-thriller",
              "AVAILABLE"),
          book(
              "9781847941831",
              "Atomic Habits",
              "James Clear",
              "Un ghid practic pentru construirea obiceiurilor bune prin schimbări mici și constante.",
              "52.00",
              "LIKE_NEW",
              "Engleză",
              "Random House",
              2018,
              "radu.georgescu@booknest.local",
              "dezvoltare-personala",
              "AVAILABLE"),
          book(
              "9780261103573",
              "Stăpânul Inelelor",
              "J.R.R. Tolkien",
              "Călătoria Frăției Inelului prin Pământul de Mijloc.",
              "64.90",
              "VERY_GOOD",
              "Română",
              "Rao",
              2012,
              "elena.marinescu@booknest.local",
              "fantasy",
              "AVAILABLE"),
          book(
              "9780553573404",
              "Urzeala tronurilor",
              "George R.R. Martin",
              "Prima parte a unei saga despre familii, putere și loialitate.",
              "44.00",
              "GOOD",
              "Română",
              "Nemira",
              2017,
              "mihai.ionescu@booknest.local",
              "fantasy",
              "AVAILABLE"),
          book(
              "9780307474278",
              "Fata cu dragon tatuat",
              "Stieg Larsson",
              "O investigație veche de decenii îi aduce împreună pe Mikael și Lisbeth.",
              "36.50",
              "ACCEPTABLE",
              "Română",
              "Trei",
              2010,
              "radu.georgescu@booknest.local",
              "mister-thriller",
              "AVAILABLE"),
          book(
              "9780385537858",
              "Inferno",
              "Dan Brown",
              "Robert Langdon descifrează indicii inspirate de Dante într-o cursă prin Florența.",
              "33.00",
              "VERY_GOOD",
              "Română",
              "Rao",
              2013,
              "elena.marinescu@booknest.local",
              "mister-thriller",
              "AVAILABLE"),
          book(
              "9780140449136",
              "Crimă și pedeapsă",
              "F.M. Dostoievski",
              "Un roman profund despre vinovăție, moralitate și izbăvire.",
              "41.90",
              "GOOD",
              "Română",
              "Penguin Classics",
              2003,
              "mihai.ionescu@booknest.local",
              "literatura-clasica",
              "AVAILABLE"),
          book(
              "9780743273565",
              "Marele Gatsby",
              "F. Scott Fitzgerald",
              "Visul american și strălucirea fragilă a epocii jazzului.",
              "28.00",
              "LIKE_NEW",
              "Engleză",
              "Scribner",
              2004,
              "radu.georgescu@booknest.local",
              "literatura-clasica",
              "AVAILABLE"),
          book(
              "9780062315007",
              "Alchimistul",
              "Paulo Coelho",
              "Povestea unui tânăr păstor aflat în căutarea propriei legende.",
              "31.50",
              "VERY_GOOD",
              "Română",
              "Humanitas Fiction",
              2014,
              "elena.marinescu@booknest.local",
              "fictiune-contemporana",
              "AVAILABLE"),
          book(
              "9780099590088",
              "Sapiens",
              "Yuval Noah Harari",
              "O incursiune accesibilă în istoria și evoluția speciei umane.",
              "55.00",
              "LIKE_NEW",
              "Română",
              "Polirom",
              2017,
              "mihai.ionescu@booknest.local",
              "istorie",
              "AVAILABLE"),
          book(
              "9780553384666",
              "Scurtă istorie a aproape tuturor lucrurilor",
              "Bill Bryson",
              "O călătorie plină de umor prin marile întrebări ale științei.",
              "49.90",
              "GOOD",
              "Română",
              "Curtea Veche",
              2016,
              "radu.georgescu@booknest.local",
              "stiinta",
              "AVAILABLE"),
          book(
              "9780062457714",
              "Arta subtilă a nepăsării",
              "Mark Manson",
              "O perspectivă directă asupra valorilor, limitelor și alegerilor personale.",
              "35.00",
              "VERY_GOOD",
              "Română",
              "Lifestyle Publishing",
              2017,
              "elena.marinescu@booknest.local",
              "dezvoltare-personala",
              "AVAILABLE"),
          book(
              "9780141321073",
              "Micul prinț",
              "Antoine de Saint-Exupéry",
              "O poveste despre prietenie, responsabilitate și lucrurile esențiale.",
              "24.90",
              "NEW",
              "Română",
              "Arthur",
              2022,
              "mihai.ionescu@booknest.local",
              "copii",
              "AVAILABLE"),
          book(
              "9780241257265",
              "Matilda",
              "Roald Dahl",
              "O fetiță extraordinară descoperă puterea cărților și curajul de a schimba lucrurile.",
              "29.50",
              "LIKE_NEW",
              "Română",
              "Arthur",
              2020,
              "radu.georgescu@booknest.local",
              "copii",
              "AVAILABLE"),
          book(
              "9780141439518",
              "Mândrie și prejudecată",
              "Jane Austen",
              "Un clasic despre orgoliu, aparențe și alegeri ale inimii.",
              "34.90",
              "GOOD",
              "Română",
              "Penguin Classics",
              2003,
              "mihai.ionescu@booknest.local",
              "literatura-clasica",
              "SOLD"),
          book(
              "9780061120084",
              "Să ucizi o pasăre cântătoare",
              "Harper Lee",
              "O poveste despre dreptate și empatie văzută prin ochii unui copil.",
              "38.50",
              "VERY_GOOD",
              "Română",
              "Polirom",
              2013,
              "elena.marinescu@booknest.local",
              "literatura-clasica",
              "SOLD"),
          book(
              "9780553380163",
              "O scurtă istorie a timpului",
              "Stephen Hawking",
              "Concepte fundamentale despre univers explicate pentru publicul larg.",
              "46.00",
              "GOOD",
              "Română",
              "Humanitas",
              2015,
              "radu.georgescu@booknest.local",
              "stiinta",
              "SOLD"));

  private DevSeedData() {}

  private static BookSeed book(
      String isbn,
      String title,
      String author,
      String description,
      String price,
      String condition,
      String language,
      String publisher,
      int publishedYear,
      String sellerEmail,
      String categorySlug,
      String status) {
    return new BookSeed(
        isbn,
        title,
        author,
        description,
        new BigDecimal(price),
        condition,
        language,
        publisher,
        (short) publishedYear,
        "https://covers.openlibrary.org/b/isbn/" + isbn + "-L.jpg",
        sellerEmail,
        categorySlug,
        status);
  }

  record UserSeed(String firstName, String lastName, String email, String role) {}

  record CategorySeed(String name, String slug, String description) {}

  record BookSeed(
      String isbn,
      String title,
      String author,
      String description,
      BigDecimal price,
      String condition,
      String language,
      String publisher,
      short publishedYear,
      String coverImageUrl,
      String sellerEmail,
      String categorySlug,
      String status) {}
}
